# Generated by Django 3.0.7 on 2020-06-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='points'),
        ),
    ]
